# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Loki
    uid: webstore-logs-loki
    type: loki
    url: http://loki:3100
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      derivedFields:
        - name: trace_id
          matcherType: label
          matcherRegex: trace_id
          url: $${__value.raw}
          datasourceUid: webstore-traces
          urlDisplayLabel: View Trace
